# 🔢 NUMPY INTERVIEW PREPARATION
# 25 Questions | Generic Technical Interview Preparation

---

## Q1. What is NumPy?

### Interview Answer

NumPy stands for Numerical Python.

It is a Python library mainly used for numerical computing and working with multidimensional arrays.

It provides powerful array operations, mathematical functions, linear algebra functionality, random number generation, and other numerical capabilities.

NumPy is also an important foundation for many Python data science libraries.

### Example

    import numpy as np

    arr = np.array([10, 20, 30])

### Memory Trick

**NumPy = Numerical Computing + Arrays**

### One-Line Answer

NumPy is a Python library for efficient numerical computing using multidimensional arrays and mathematical operations.

---

## Q2. What is a NumPy array?

### Interview Answer

A NumPy array is a data structure provided by NumPy for storing numerical or other homogeneous data in one or more dimensions.

Unlike a normal Python list, NumPy arrays are designed for efficient numerical operations and support vectorized computation.

### Example

    import numpy as np

    arr = np.array([10, 20, 30])

### Memory Trick

**NumPy Array = Efficient Data Container**

### One-Line Answer

A NumPy array is a multidimensional array structure optimized for numerical computation.

---

## Q3. What is the difference between a Python list and a NumPy array?

### Interview Answer

A Python list can store elements of different data types and is a general-purpose data structure.

A NumPy array is primarily designed for numerical computation and generally stores elements of a common data type.

NumPy arrays also support vectorized operations and are generally more memory-efficient and faster for many large numerical computations.

### Example

    Python List:

    [1, 2, 3]

    NumPy Array:

    np.array([1, 2, 3])

### Memory Trick

**List = General Purpose**

**NumPy Array = Numerical Operations**

### One-Line Answer

Python lists are general-purpose containers, while NumPy arrays are optimized for efficient numerical and vectorized computation.

---

## Q4. What are the dimensions of a NumPy array?

### Interview Answer

A NumPy array can have multiple dimensions.

Common examples are:

- 0D → Scalar
- 1D → Vector
- 2D → Matrix
- 3D → Tensor-like structure

### Example

    0D:
    np.array(10)

    1D:
    np.array([1, 2, 3])

    2D:
    np.array([
        [1, 2],
        [3, 4]
    ])

### Memory Trick

**0D → Scalar**

**1D → Vector**

**2D → Matrix**

**3D+ → Higher Dimensions**

### One-Line Answer

NumPy arrays can have zero, one, two, or higher dimensions depending on how the data is structured.

---

## Q5. What are shape, size, ndim, and dtype?

### Interview Answer

These are important NumPy array attributes.

`shape` tells us the size of the array along each dimension.

`size` tells us the total number of elements.

`ndim` tells us the number of dimensions.

`dtype` tells us the data type of the elements.

### Example

    arr = np.array([
        [1, 2, 3],
        [4, 5, 6]
    ])

    arr.shape
    → (2, 3)

    arr.size
    → 6

    arr.ndim
    → 2

    arr.dtype
    → integer type

### Memory Trick

**shape = Structure**

**size = Elements**

**ndim = Dimensions**

**dtype = Data Type**

### One-Line Answer

`shape` gives dimensions, `size` gives total elements, `ndim` gives number of dimensions, and `dtype` gives the element data type.

---

## Q6. How do you create a NumPy array?

### Interview Answer

We can create a NumPy array using `np.array()`.

It can accept Python lists, tuples, or other array-like objects.

### Example

    import numpy as np

    arr = np.array([10, 20, 30])

    matrix = np.array([
        [1, 2],
        [3, 4]
    ])

### Memory Trick

**np.array() = Create Array**

### One-Line Answer

I use `np.array()` to create a NumPy array from list-like or other array-like data.

---

## Q7. What is the difference between np.array() and np.asarray()?

### Interview Answer

Both can convert array-like objects into NumPy arrays.

`np.array()` generally creates a new array unless copying can safely be avoided under the selected options.

`np.asarray()` is designed to avoid an unnecessary copy when the input is already a NumPy array with a compatible dtype and memory layout.

Therefore, `asarray()` can be useful when we want to avoid unnecessary copying.

### Memory Trick

**array = Create**

**asarray = Avoid Unnecessary Copy**

### One-Line Answer

Both convert data to NumPy arrays, but `np.asarray()` is designed to avoid unnecessary copying when possible.

---

## Q8. How do you create arrays of zeros and ones?

### Interview Answer

NumPy provides `np.zeros()` and `np.ones()`.

### Example

    np.zeros((2, 3))

    Output:
    [[0. 0. 0.]
     [0. 0. 0.]]

    np.ones((2, 3))

    Output:
    [[1. 1. 1.]
     [1. 1. 1.]]

These functions are useful for initialization and numerical computations.

### Memory Trick

**zeros = 0**

**ones = 1**

### One-Line Answer

I use `np.zeros()` and `np.ones()` to create arrays initialized with zeros or ones.

---

## Q9. What is np.arange()?

### Interview Answer

`np.arange()` creates values within a specified range using a step size.

It is similar to Python's `range()`, but returns a NumPy array.

### Example

    np.arange(0, 10, 2)

    Output:

    [0 2 4 6 8]

The stop value is normally excluded.

### Memory Trick

**arange = Start + Stop + Step**

### One-Line Answer

`np.arange()` creates evenly spaced values within a range using a specified step size.

---

## Q10. What is np.linspace()?

### Interview Answer

`np.linspace()` generates a specified number of evenly spaced values between a start and end point.

Unlike `arange()`, we specify the number of values rather than the step size.

### Example

    np.linspace(0, 10, 5)

    Output:

    [ 0.   2.5  5.   7.5 10. ]

### Memory Trick

**linspace = Number of Values**

**arange = Step Size**

### One-Line Answer

`np.linspace()` generates a specified number of evenly spaced values between two endpoints.

---

## Q11. What is reshaping in NumPy?

### Interview Answer

Reshaping changes the dimensions of an array without changing its data, provided the total number of elements remains compatible.

The `reshape()` method is commonly used.

### Example

    arr = np.array([1, 2, 3, 4, 5, 6])

    arr.reshape(2, 3)

    Output:

    [[1 2 3]
     [4 5 6]]

The original array has 6 elements, and the new shape also contains 6 positions.

### Memory Trick

**Reshape = Change Structure, Not Data**

### One-Line Answer

Reshaping changes an array's dimensions while preserving its elements when the new shape is compatible.

---

## Q12. What is flatten()?

### Interview Answer

`flatten()` converts a multidimensional array into a one-dimensional array.

It returns a copy of the data.

### Example

    arr = np.array([
        [1, 2],
        [3, 4]
    ])

    arr.flatten()

    Output:

    [1 2 3 4]

### Memory Trick

**flatten = 2D → 1D Copy**

### One-Line Answer

`flatten()` converts a multidimensional array into a one-dimensional copy.

---

## Q13. What is the difference between flatten() and ravel()?

### Interview Answer

Both convert an array into one dimension.

The important difference is that `flatten()` always returns a copy, while `ravel()` returns a flattened view when possible and may therefore avoid copying.

Changes made through a view can affect the original array, depending on the situation.

### Memory Trick

**flatten = Copy**

**ravel = View when possible**

### One-Line Answer

`flatten()` returns a copy, while `ravel()` may return a view when possible.

---

## Q14. What is indexing and slicing in NumPy?

### Interview Answer

Indexing is used to access specific elements, while slicing is used to access a range or subset of elements.

NumPy supports indexing and slicing across multiple dimensions.

### Example

    arr = np.array([10, 20, 30, 40])

    arr[1]

    → 20

    arr[1:3]

    → [20 30]

For a 2D array:

    arr[0, 1]

    → Element at row 0, column 1

### Memory Trick

**Index = Specific**

**Slice = Range**

### One-Line Answer

NumPy indexing accesses specific elements, while slicing accesses a subset or range of elements.

---

## Q15. What is boolean indexing in NumPy?

### Interview Answer

Boolean indexing allows us to select elements based on a condition.

It creates a Boolean mask and uses that mask to retrieve matching elements.

### Example

    arr = np.array([10, 20, 30, 40])

    arr[arr > 20]

    Output:

    [30 40]

### Memory Trick

**Condition → Mask → Filter**

### One-Line Answer

Boolean indexing filters NumPy arrays using Boolean conditions.

---

## Q16. What is vectorization in NumPy?

### Interview Answer

Vectorization means performing an operation on an entire array instead of explicitly writing a Python loop for each element.

NumPy implements many operations efficiently at the array level.

### Example

Instead of:

    result = []

    for x in arr:
        result.append(x * 2)

We can write:

    result = arr * 2

### Memory Trick

**Vectorization = No Explicit Element Loop**

### One-Line Answer

Vectorization allows operations to be performed on entire arrays efficiently without explicitly looping through individual elements in Python.

---

## Q17. What is broadcasting in NumPy?

### Interview Answer

Broadcasting is NumPy's mechanism for performing operations on arrays with compatible but different shapes.

NumPy automatically adjusts the smaller array conceptually across compatible dimensions so that the operation can be performed.

### Example

    arr = np.array([
        [1, 2, 3],
        [4, 5, 6]
    ])

    arr + 10

    Output:

    [[11 12 13]
     [14 15 16]]

The scalar `10` is effectively applied to every element.

### Memory Trick

**Broadcasting = Compatible Shapes Work Together**

### One-Line Answer

Broadcasting allows NumPy to perform operations between arrays with compatible shapes without manually reshaping every array.

---

## Q18. What are universal functions (ufuncs) in NumPy?

### Interview Answer

Universal functions, or ufuncs, are NumPy functions that operate element-wise on arrays.

They are designed for efficient numerical operations.

Examples include:

    np.sqrt()
    np.exp()
    np.sin()
    np.add()
    np.multiply()

### Example

    arr = np.array([1, 4, 9])

    np.sqrt(arr)

    Output:

    [1. 2. 3.]

### Memory Trick

**ufunc = Element-wise NumPy Function**

### One-Line Answer

Universal functions are NumPy functions designed to efficiently perform element-wise operations on array data.

---

## Q19. What are aggregation functions in NumPy?

### Interview Answer

Aggregation functions summarize array data into one or more values.

Common functions include:

    np.sum()
    np.mean()
    np.median()
    np.min()
    np.max()
    np.std()
    np.var()

### Example

    arr = np.array([10, 20, 30, 40])

    np.mean(arr)
    → 25

    np.sum(arr)
    → 100

### Memory Trick

**Aggregation = Summarize Data**

### One-Line Answer

NumPy aggregation functions summarize numerical data using operations such as sum, mean, minimum, maximum, variance, and standard deviation.

---

## Q20. What is the axis parameter in NumPy?

### Interview Answer

The `axis` parameter specifies the direction along which an operation is performed.

For a 2D array:

    axis=0
    → Operate down rows / across each column

    axis=1
    → Operate across columns / for each row

### Example

    arr = np.array([
        [1, 2, 3],
        [4, 5, 6]
    ])

    np.sum(arr, axis=0)

    → [5 7 9]

    np.sum(arr, axis=1)

    → [6 15]

### Memory Trick

**axis=0 → Column-wise Result**

**axis=1 → Row-wise Result**

### One-Line Answer

The `axis` parameter specifies the dimension along which a NumPy operation is performed.

---

## Q21. What is the difference between a view and a copy in NumPy?

### Interview Answer

A copy creates a separate array containing its own data.

A view provides another way of accessing the same underlying data when possible.

Therefore, modifying a view may affect the original array, while modifying an independent copy does not.

### Example

    arr = np.array([1, 2, 3, 4])

    view = arr[1:3]

    copy = arr[1:3].copy()

A change to `view` may affect `arr`, while a change to `copy` does not affect the original.

### Memory Trick

**View = Same Data**

**Copy = Separate Data**

### One-Line Answer

A view can share the original array's underlying data, while a copy creates independent data.

---

## Q22. How do you combine NumPy arrays?

### Interview Answer

NumPy provides several functions for combining arrays.

Common functions include:

    np.concatenate()
    np.vstack()
    np.hstack()
    np.stack()

`concatenate()` joins arrays along an existing axis.

`vstack()` stacks arrays vertically.

`hstack()` stacks arrays horizontally.

`stack()` joins arrays along a new axis.

### Example

    a = np.array([1, 2])
    b = np.array([3, 4])

    np.concatenate([a, b])

    → [1 2 3 4]

### Memory Trick

**concatenate = Existing Axis**

**stack = New Axis**

**vstack = Vertical**

**hstack = Horizontal**

### One-Line Answer

NumPy provides functions such as `concatenate()`, `vstack()`, `hstack()`, and `stack()` for combining arrays.

---

## Q23. What is random number generation in NumPy?

### Interview Answer

NumPy provides random number generation functionality through `numpy.random`.

The modern recommended approach is to create a random generator using `np.random.default_rng()` and then use its methods.

### Example

    rng = np.random.default_rng(42)

    values = rng.integers(
        1,
        100,
        size=5
    )

A seed can be used to make results reproducible.

### Memory Trick

**default_rng = Modern Random Generator**

### One-Line Answer

NumPy provides random number generation through `numpy.random`, with `default_rng()` being the modern recommended generator interface.

---

## Q24. What is the difference between np.random.seed() and default_rng()?

### Interview Answer

`np.random.seed()` sets the seed for NumPy's legacy global random state.

`np.random.default_rng()` creates a dedicated random number generator object.

The generator-based approach is generally preferred in modern code because it provides better control over independent random streams and avoids relying on shared global state.

### Example

    rng = np.random.default_rng(42)

    rng.random(5)

### Memory Trick

**seed = Legacy Global State**

**default_rng = Modern Generator**

### One-Line Answer

`default_rng()` provides a modern generator-based random number interface, while `np.random.seed()` controls the legacy global random state.

---

## Q25. How is NumPy used in a machine learning project?

### Interview Answer

NumPy is commonly used for numerical computation and array manipulation within machine learning workflows.

A typical workflow can look like:

    Raw Data
        ↓
      Pandas
        ↓
    Cleaning
        ↓
      NumPy
        ↓
    Numerical Transformation
        ↓
    Feature Arrays
        ↓
    Scikit-learn / Deep Learning
        ↓
      Model
        ↓
    Predictions

NumPy can be used for mathematical operations, matrix operations, array transformations, numerical preprocessing, and handling model inputs.

### Memory Trick

**Pandas → Data**

**NumPy → Numbers**

**Scikit-learn → ML**

### One-Line Answer

I use NumPy for efficient numerical computation, array manipulation, mathematical operations, and preparing numerical data for machine learning models.


# 🧠 NUMPY MASTER FLOW

    Data
      ↓
    NumPy Array
      ↓
    Inspect
      ↓
    Index / Slice
      ↓
    Filter
      ↓
    Transform
      ↓
    Vectorize
      ↓
    Broadcast
      ↓
    Aggregate
      ↓
    ML / Numerical Computation


# 🎯 NUMPY KEY CONCEPTS

**ndarray**
→ NumPy's primary array object

**shape**
→ Size along each dimension

**size**
→ Total number of elements

**ndim**
→ Number of dimensions

**dtype**
→ Data type of elements

**reshape()**
→ Change dimensions

**flatten()**
→ Flatten and copy

**ravel()**
→ Flatten, view when possible

**indexing**
→ Access elements

**slicing**
→ Access subsets

**boolean indexing**
→ Condition-based filtering

**vectorization**
→ Array-level operations

**broadcasting**
→ Operations across compatible shapes

**ufunc**
→ Element-wise NumPy function

**axis**
→ Direction of an operation

**view**
→ May share underlying data

**copy**
→ Independent data


# 🔥 MOST IMPORTANT NUMPY FUNCTIONS

    import numpy as np

    np.array()
    np.asarray()

    np.zeros()
    np.ones()
    np.empty()

    np.arange()
    np.linspace()

    np.reshape()
    np.ravel()
    np.flatten()

    np.concatenate()
    np.vstack()
    np.hstack()
    np.stack()

    np.sum()
    np.mean()
    np.median()
    np.min()
    np.max()
    np.std()
    np.var()

    np.sqrt()
    np.exp()
    np.sin()

    np.random.default_rng()


# 🧠 NUMPY TROUBLESHOOTING FORMULA

When an interviewer gives you a NumPy problem:

**1. Inspect**

    arr.shape
    arr.ndim
    arr.size
    arr.dtype

**2. Understand Structure**

    1D?
    2D?
    3D?
    Compatible Shapes?

**3. Select Data**

    Indexing
    Slicing
    Boolean Mask

**4. Transform**

    reshape
    transpose
    astype

**5. Compute**

    Vectorization
    Broadcasting
    Aggregation

**6. Validate**

    shape
    dtype
    values


# 🏆 PANDAS + NUMPY CONNECTION

Remember this important relationship:

    Raw Dataset
        ↓
      Pandas
        ↓
    DataFrame
        ↓
    Cleaning
        ↓
      NumPy
        ↓
    Numerical Arrays
        ↓
    Scikit-learn
        ↓
    Machine Learning Model


# ⭐ INTERVIEW GOLDEN POINT

If an interviewer asks:

**"Why use NumPy instead of Python lists?"**

A strong answer is:

**"NumPy is specifically designed for numerical computing. Its multidimensional arrays support vectorized operations, broadcasting, and efficient numerical processing, which makes it more suitable than Python lists for large-scale numerical workloads."**


# 🎯 IMPORTANT DISTINCTION

**Python List**
→ General-purpose collection

**NumPy Array**
→ Numerical computation

**Pandas DataFrame**
→ Structured/tabular data

**Matplotlib / Seaborn / Plotly**
→ Visualization

**Scikit-learn**
→ Machine Learning


# 🔥 FINAL MEMORY MAP

    Python
       ↓
    NumPy
       ↓
    Numerical Arrays
       ↓
    Pandas
       ↓
    Structured Data
       ↓
    Scikit-learn
       ↓
    Machine Learning

Or remember:

**NumPy → Numbers**

**Pandas → Tables**

**Scikit-learn → Machine Learning**